### ISSUE TITLE
Controller Mode

### ISSUE THREAD

**Issue by Ervalord** [insthync/UnityMultiplayerARPG_TopDownController#4]
Can´t change the state over Controller Mode.
If i choose WASD on the prefab and save it, and then run the kit,  the controller mode has automatic gone to the state of " Point and Click) and i can´t change that state.
![Controller_Mode](https://user-images.githubusercontent.com/56819674/198132846-d3c7da8a-7523-48a2-82db-a412bbb9b126.JPG)

**Comment by insthync** [comment]
It works as intended, this top-down is made for point click only, I don't know how you expect it to work.

**Comment by Ervalord** [comment]
Ok, i see, my bad.
I guess i was a bit confused by the dropdown to choose state.
